### ISSUE TITLE
Issue with JTE (also migrated to 2.0?)

### ISSUE THREAD

**Issue by tipsy** [javalin/javalin-rendering#1]
@casid could you have a look?

**Comment by tipsy** [comment]
```
Error:  Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:testCompile (default-testCompile) on project javalin-rendering: Compilation failure: Compilation failure: 
Error:  /Users/runner/work/javalin-rendering/javalin-rendering/src/test/kotlin/io/javalin/jte/precompiled/JtetestGenerated.java:[3,32] package io.javalin.TestTemplates does not exist
Error:  /Users/runner/work/javalin-rendering/javalin-rendering/src/test/kotlin/io/javalin/jte/precompiled/JtetestGenerated.java:[9,121] cannot find symbol
Error:    symbol:   class JteTestPage
Error:    location: class io.javalin.jte.precompiled.JtetestGenerated
```

**Comment by tipsy** [comment]
Tests work fine locally.

**Comment by casid** [comment]
That's odd, I'll check out the repo and have a look at it.

Also, yes, there was bump to version 2.x, because of a breaking change how to call other templates. There's some details here: https://github.com/casid/jte/releases/tag/2.0.0 Migration of existing templates is semi-automatically, the engine detects old templates and spits out code to migrate them, so it's not too bad.

Can do a PR to the latest version if you want to. Is this a separate repo, where you're moving the template integrations to?

**Comment by tipsy** [comment]
> Can do a PR to the latest version if you want to. Is this a separate repo, where you're moving the template integrations to?

Thank you! For Javalin5 all template engines will be found in the `javalin-rendering` artifact, which will live in this repo :)

**Comment by tipsy** [comment]
Thanks @casid !
